const AdProductDetail = (product)=>{
    return(
        <div className="">
            {product.name}
            모달창
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
            <div>모달창</div>
        </div>
    );
}
export default AdProductDetail;